name: ${DOCKER_NAME}
services:
  nginx:
    image: 'nginx:1.21.3'
    ports:
      - '${HTTP_BIND}:${HTTP_PORT}:80'
    volumes:
      - ./.huly.nginx:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    links:
      - account
      - transactor
      - front
      - stats
    networks:
      - huly_net

  postgres:
    image: postgres:18.1
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUME_POSTGRES_DATA_PATH:-postgres_data}:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - huly_net

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v25.2.11
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --smp 1
      - --default-log-level=info
    volumes:
      - ${VOLUME_REDPANDA_PATH:-redpanda}:/var/lib/redpanda/data
    environment:
      - REDPANDA_SUPERUSER_USERNAME=${REDPANDA_ADMIN_USER}
      - REDPANDA_SUPERUSER_PASSWORD=${REDPANDA_ADMIN_PWD}
    healthcheck:
      test:
        [
          'CMD',
          'rpk',
          'cluster',
          'info',
          '-X',
          'user=${REDPANDA_ADMIN_USER}',
          '-X',
          'pass=${REDPANDA_ADMIN_PWD}',
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - huly_net

  minio:
    image: 'minio/minio'
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - ${VOLUME_FILES_PATH:-files}:/data
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - huly_net

  elastic:
    image: 'elasticsearch:7.14.2'
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - ${VOLUME_ELASTIC_PATH:-elastic}:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped
    networks:
      - huly_net

  rekoni:
    image: haiodo/rekoni-service:${HULY_VERSION}
    environment:
      - SECRET=${SECRET}
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    networks:
      - huly_net

  transactor:
    image: haiodo/transactor:${HULY_VERSION}
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - FRONT_URL=http://localhost:8087
      - ACCOUNTS_URL=http://account:3000
      - FULLTEXT_URL=http://fulltext:4700
      - STATS_URL=http://stats:4900
      - LAST_NAME_FIRST=${LAST_NAME_FIRST:-true}
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped
    networks:
      - huly_net

  collaborator:
    image: haiodo/collaborator:${HULY_VERSION}
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=${SECRET}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - STORAGE_CONFIG=${STORAGE_CONFIG}
    restart: unless-stopped
    networks:
      - huly_net

  account:
    image: haiodo/account:${HULY_VERSION}
    links:
      - postgres
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=${SECRET}
      - ADMIN_EMAILS=${PLATFORM_ADMIN_EMAILS}
      - DB_URL=${CR_DB_URL}
      - TRANSACTOR_URL=ws://transactor:3333;ws${SECURE:+s}://${HOST_ADDRESS}/_transactor
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - FRONT_URL=http${SECURE:+s}://${HOST_ADDRESS}
      - STATS_URL=http://stats:4900
      - STATS_API=http${SECURE:+s}://${HOST_ADDRESS}/_stats
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http${SECURE:+s}://${HOST_ADDRESS}/_accounts
      - ACCOUNT_PORT=3000
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped
    networks:
      - huly_net

  workspace:
    image: haiodo/workspace:${HULY_VERSION}
    environment:
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - TRANSACTOR_URL=ws://transactor:3333;ws${SECURE:+s}://${HOST_ADDRESS}/_transactor
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - QUEUE_CONFIG=redpanda:9092
      - ACCOUNTS_DB_URL=${CR_DB_URL}
    restart: unless-stopped
    networks:
      - huly_net

  front:
    image: haiodo/front:${HULY_VERSION}
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=${SECRET}
      - LOVE_ENDPOINT=http${SECURE:+s}://${HOST_ADDRESS}/_love
      - ACCOUNTS_URL=http${SECURE:+s}://${HOST_ADDRESS}/_accounts
      - ACCOUNTS_URL_INTERNAL=http://account:3000
      - REKONI_URL=http${SECURE:+s}://${HOST_ADDRESS}/_rekoni
      - CALENDAR_URL=http${SECURE:+s}://${HOST_ADDRESS}/_calendar
      - GMAIL_URL=http${SECURE:+s}://${HOST_ADDRESS}/_gmail
      - TELEGRAM_URL=http${SECURE:+s}://${HOST_ADDRESS}/_telegram
      - STATS_URL=http://stats:4900
      - STATS_API=http${SECURE:+s}://${HOST_ADDRESS}/_stats
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=ws${SECURE:+s}://${HOST_ADDRESS}/_collaborator
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - TITLE=${TITLE:-Huly Self Host}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-en}
      - LAST_NAME_FIRST=${LAST_NAME_FIRST:-true}
      - DESKTOP_UPDATES_CHANNEL=${DESKTOP_CHANNEL}
      - PULSE_URL=ws${SECURE:+s}://${HOST_ADDRESS}/_pulse
      - STREAM_URL=http${SECURE:+s}://${HOST_ADDRESS}/_stream/recording
      - PREVIEW_URL=http${SECURE:+s}://${HOST_ADDRESS}/_preview
      - DATALAKE_URL=http${SECURE:+s}://${HOST_ADDRESS}/_datalake
      - FILES_URL=http${SECURE:+s}://${HOST_ADDRESS}/_datalake/blob/:workspace/:blobId/:filename
      - LIVEKIT_WS=${LIVEKIT_HOST}
    restart: unless-stopped
    networks:
      - huly_net
  datalake:
    image: haiodo/datalake:${HULY_VERSION}
    extra_hosts:
      - 'huly.local:host-gateway'
    depends_on:
      minio:
        condition: service_healthy
      postgres:
        condition: service_started
      stats:
        condition: service_started
      account:
        condition: service_started
    ports:
      - 4031:4031
    environment:
      - PORT=4031
      - SECRET=${SECRET}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - DB_URL=${CR_DB_URL}
      - BUCKETS=blobs,eu|http://minio:9000?accessKey=minioadmin&secretKey=minioadmin
      - QUEUE_CONFIG=redpanda:9092
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318/v1/traces
    restart: unless-stopped
    networks:
      - huly_net
  fulltext:
    image: haiodo/fulltext:${HULY_VERSION}
    environment:
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - FULLTEXT_DB_URL=http://elastic:9200
      - ELASTIC_INDEX_NAME=huly_storage_index
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - REKONI_URL=http://rekoni:4004
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped
    networks:
      - huly_net

  stats:
    image: haiodo/stats:${HULY_VERSION}
    environment:
      - PORT=4900
      - SERVER_SECRET=${SECRET}
    restart: unless-stopped
    networks:
      - huly_net

  rating:
    image: haiodo/rating:${HULY_VERSION}
    extra_hosts:
      - 'huly.local:host-gateway'
    links:
      - postgres
      - minio
      - account
      - stats
    depends_on:
      redpanda:
        condition: service_started
    environment:
      - QUEUE_CONFIG=redpanda:9092
      - SERVER_SECRET=${SECRET}
      - STATS_URL=http://stats:4900
      - DB_URL=${CR_DB_URL}
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - ACCOUNTS_URL=http://account:3000
      - COMMUNICATION_TIME_LOGGING_ENABLED=true
      - COMMUNICATION_API_ENABLED=false
    restart: unless-stopped
    networks:
      - huly_net
  redis:
    image: redis:8.0.2-alpine3.21
    restart: unless-stopped
    networks:
      - huly_net
  hulypulse:
    image: haiodo/hulypulse:${HULY_VERSION}
    depends_on:
      redis:
        condition: service_started
    ports:
      - 8098:8098
    environment:
      - HULY_TOKEN_SECRET=${SECRET}
      - HULY_REDIS_URLS=redis://redis:6379
      - HULY_BIND_PORT=8098
      - HULY_REDIS_MODE=direct
    restart: unless-stopped
    networks:
      - huly_net

  process-service:
    image: haiodo/process:${HULY_VERSION}
    extra_hosts:
      - 'huly.local:host-gateway'
    depends_on:
      redpanda:
        condition: service_started
      account:
        condition: service_started
    environment:
      - SECRET=secret
      - ACCOUNTS_URL=http://account:3000
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped
    networks:
      - huly_net

  stream:
    image: 'haiodo/stream:${HULY_VERSION}'
    extra_hosts:
      - 'huly.local:host-gateway'
    environment:
      #      - STREAM_ENDPOINT_URL=s3://minio
      - STREAM_ENDPOINT_URL=datalake://datalake:4031
      - STREAM_INSECURE=true
      - STREAM_SERVER_SECRET=${SECRET}
      - STREAM_BASE_URL=http${SECURE:+s}://${HOST_ADDRESS}/_stream
      - STREAM_MAX_PARALLEL_SCALING_COUNT=2
      - STREAM_LOG_LEVEL=debug
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - STREAM_QUEUE_CONFIG=redpanda:9092
    ports:
      - 1081:1080
    restart: unless-stopped
    networks:
      - huly_net
  media:
    image: 'haiodo/media:${HULY_VERSION}'
    extra_hosts:
      - 'huly.local:host-gateway'
    environment:
      - ACCOUNTS_URL=http://account:3000
      - SECRET=${SECRET}
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped
    networks:
      - huly_net
  preview:
    image: 'haiodo/preview:${HULY_VERSION}'
    extra_hosts:
      - 'huly.local:host-gateway'
    environment:
      - SECRET=${SECRET}
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - CACHE_PATH=/data/cache
    ports:
      - 4041:4040
    restart: unless-stopped
    networks:
      - huly_net

  love:
    image: haiodo/love:${HULY_VERSION}
    extra_hosts:
      - 'huly.local:host-gateway'
    environment:
      - PORT=8096
      - SECRET=${SECRET}
      - ACCOUNTS_URL=http://account:3000
      - DB_URL=${CR_DB_URL}
      - STORAGE_CONFIG=${STORAGE_CONFIG}
      - STORAGE_PROVIDER_NAME=minio
      - LIVEKIT_HOST=${LIVEKIT_HOST}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - huly_net
volumes:
  # These named volumes are used when custom volume paths are not specified
  # If VOLUME_*_PATH variables are set, these volumes will be ignored
  elastic:
  files:
  postgres_data:
  redpanda:

networks:
  huly_net:
